// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCareerPath.Infrastructure.Persistence.Data;

#nullable disable

namespace SmartCareerPath.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130123000_FixPaymentTransactionCurrencyType")]
    partial class FixPaymentTransactionCurrencyType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a minimal designer file to allow EF to recognize the migration.
            // The actual schema snapshot is maintained in ApplicationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
